#pragma once

#define CORE_FREQ_HZ 150000000

typedef enum {
  STATUS_CODE_OK = 0,
  STATUS_CODE_INVALID_ARGS = -1,
  STATUS_CODE_NOT_INITIALIZED = -2,
  STATUS_CODE_ALREADY_INITIALIZED = -3,
  STATUS_CODE_MEM_ACCESS_FAILURE = -4,
  STATUS_CODE_FAILED = -5,
} StatusCode;